server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:mysql://localhost:3306/leetcode_tracker?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never

logging:
  level:
    com.leetcode.tracker: INFO
